### ISSUE TITLE
Android - UseDragSort exception: Queue empty

### ISSUE THREAD

**Issue by matteopiccioni** [muak/AiForms.SettingsView#133]
### Description
SettingsView with UseDragSort = true into a Section
If I drag and drop an item in the same row (only releasing finger) the app crashes

### Steps to Reproduce

1. 
Create a SettingsView view with UseDragSort = true into a Section
2.
Tap down a row with a finger
3. 
Release the finger

### Expected Behavior
App should not crash

### Actual Behavior
App crashes

### Platforms

- [x] Android
- [ ] iOS

### Basic Information

- AiForms.SettingsView 1.3.1
- Xamarin.Forms 4.84.0.1451

Exception:
```
System.InvalidOperationException
Queue empty.

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.InvalidOperationException: Queue empty.
[MonoDroid]   at AndroidX.RecyclerView.Widget.ItemTouchHelper+Callback.n_ClearView_Landroidx_recyclerview_widget_RecyclerView_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_recyclerView, System.IntPtr native_viewHolder) [0x00017] in <2168258d9109410-02 13:57:44.432 I/MonoDroid( 7687):   at System.Collections.Generic.Queue`1[T].Peek () [0x00008] in <7c7edee739e146c2a59ba18fce0f454b>:0 
[MonoDroid]   at AiForms.Renderers.Droid.SettingsViewSimpleCallback.DataSourceMoved () [0x00000] in <61d8169ad485489c8bff1a71d562f7af>:0 
[MonoDroid]   at AiForms.Renderers.Droid.SettingsViewSimpleCallback.ClearView (AndroidX.RecyclerView.Widget.RecyclerView recyclerView, AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder viewHolder) [0x00038] in <61d8169ad485489c8bff1a71d562f7af>:0 
[MonoDroid]   at AndroidX.RecyclerView.Widget.ItemTouchHelper+Callback.n_ClearView_Landroidx_recyclerview_widget_RecyclerView_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_recyclerView, System.IntPtr native_viewHolder) [0x00017] in <2168258d9109409a83a9b41718abf172>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.140(intptr,intptr,intptr,intptr)
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: my.packagename, PID: 7687
[AndroidRuntime]   at AndroidX.RecyclerView.Widget.ItemTouchH10-02 13:57:44.489 E/AndroidRuntime( 7687): android.runtime.JavaProxyThrowable: System.InvalidOperationException: Queue empty.
[AndroidRuntime]   at System.Collections.Generic.Queue`1[T].Peek () [0x00008] in <7c7edee739e146c2a59ba18fce0f454b>:0 
[AndroidRuntime]   at AiForms.Renderers.Droid.SettingsViewSimpleCallback.DataSourceMoved () [0x00000] in <61d8169ad485489c8bff1a71d562f7af>:0 
[AndroidRuntime]   at AiForms.Renderers.Droid.SettingsViewSimpleCallback.ClearView (AndroidX.RecyclerView.Widget.RecyclerView recyclerView, AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder viewHolder) [0x00038] in <61d8169ad485489c8bff1a71d562f7af>:0 
[AndroidRuntime] 	at crc6484fad89fba26ff1d.SettingsViewSimpleCallback.n_clearView(Native Method)
[AndroidRuntime] 	at crc6484fad89fba26ff1d.SettingsViewSimpleCallback.clearView(SettingsViewSimpleCallback.java:41)
[AndroidRuntime] 	at androidx.recyclerview.widget.ItemTouchHelper$3.onAnimationEnd(ItemTouchHelper.java:644)
[AndroidRuntime] 	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
[AndroidRuntime] 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1485)
[AndroidRuntime] 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
[AndroidRuntime] 	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
[AndroidRuntime] 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
[AndroidRuntime] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1027)
[AndroidRuntime] 	at android.view.Choreographer.doCallbacks(Choreographer.java:852)
[AndroidRuntime] 	at android.view.Choreographer.doFrame(Choreographer.java:783)
[AndroidRuntime] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:883)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7397)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
[Process] Sending signal. PID: 7687 SIG: 9

```

**Comment by muak** [comment]
@matteopiccioni 

Thank you for your report.

I fixed just now.

Please wait for version 1.3.2.
